language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t peterorliczki/code-mates-spring -f ./src/main/docker/Dockerfile ./src/main/docker

script:
  - docker run -e CI=true peterorliczki/code-mates-spring mvn clean test

after_success:
  - docker build -t peterorliczki/code-mates-spring ./src/main/docker
  # Docker CLI login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Image pushing to docker hub
  - docker push peterorliczki/code-mates-spring